database_in=file:/var/lib/aide/aide.db.gz
database_out=file:/var/lib/aide/aide.db.new.gz
database_new=file:/var/lib/aide/aide.db.new.gz

gzip_dbout=yes

report_url=stdout
report_level=changed_attributes

NORMAL = p+i+n+u+g+s+m+c+sha512
BOOT = p+n+u+g+s+m+c+sha512
DIR = p+i+n+u+g
LOG = p+u+g+n

/boot                       BOOT
/etc                        NORMAL
/usr/bin                    NORMAL
/usr/sbin                   NORMAL
/usr/lib                    NORMAL
/usr/lib64                  NORMAL
/usr/local/bin              NORMAL
/usr/local/sbin             NORMAL
/usr/local/lib              NORMAL
/root                       NORMAL

!/proc
!/sys
!/dev
!/run
!/tmp
!/var/tmp
!/var/cache
!/var/log
!/home/.cache
