title Arch Linux (Fallback)
linux /vmlinuz-linux-hardened
initrd /amd-ucode.img
initrd /initramfs-linux-hardened-fallback.img
options rd.luks.name=b9395317-32df-46a1-b6f3-464edb94d893=root root=/dev/mapper/root rw quiet splash amdgpu.modeset=1 loglevel=3 slab_nomerge init_on_alloc=1 init_on_free=1 mitigations=auto,nosmt lsm=landlock,lockdown,yama,integrity,apparmor,bpf apparmor=1 security=apparmor audit=1
