title Arch Linux
linux /vmlinuz-linux-zen
initrd /amd-ucode.img
initrd /initramfs-linux-zen.img
options rd.luks.name=9ad6ebc9-dfd2-4ba1-881b-dd9f22eeedb4=root root=/dev/mapper/root rw quiet splash nvidia.NVreg_OpenRmEnable=1 nvidia_drm.modeset=1 nvidia_drm.fbdev=1 nvidia.NVreg_EnableGpuFirmware=0 nvidia.NVreg_PreserveVideoMemoryAllocations=1 loglevel=3 slab_nomerge init_on_alloc=1 init_on_free=1 mitigations=auto,nosmt lsm=landlock,lockdown,yama,integrity,apparmor,bpf apparmor=1 security=apparmor audit=1
